### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by CrazyWolf13** [Lortseam/completeconfig#7]
Tested various versions. Does not work!
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
[crash-2023-01-15_12.41.00-client.txt](https://github.com/Lortseam/completeconfig/files/10420045/crash-2023-01-15_12.41.00-client.txt)
[latest.log](https://github.com/Lortseam/completeconfig/files/10420047/latest.log)
@Lortseam

**Comment by Lortseam** [comment]
Are you sure CompleteConfig is causing this crash? Please try to remove CompleteConfig and see if the game still crashes.

Edit: Also, for 1.19.2 you need CompleteConfig version 2.1.0.

**Comment by CrazyWolf13** [comment]
> Are you sure CompleteConfig is causing this crash? Please try to remove CompleteConfig and see if the game still crashes.

Thank you for the answer.
Actually no, i want to use Player Highlighter which requires Complete config. And if i normally install both of them via curseforge application, the fabric crash screen shows up and says that complete config has to be 2.2.0 (which is 1.19.3, but i'm playing on1.19.2) Which already confused me a lot, then i downloaded the 2.2.0 version normally through the website but then the game wouldn't launch at all, and there were some confusing fabric indigo renderer errors, so i'm unsure which mod is the fault, but if you say this i'd rather think it's Player Highlighter.

**Comment by Lortseam** [comment]
Please try version 2.2.1 of PlayerHighlighter, that should probably work on 1.19.2.

**Comment by CrazyWolf13** [comment]
Did also try with that version, same error

> Please try version 2.2.1 of PlayerHighlighter, that should probably work on 1.19.2.

**Comment by Lortseam** [comment]
Then you probably need to play on 1.19.1 or 1.19.3, or you could ask the developer of PlayerHighlighter to publish a version for 1.19.2.
